export const ADDRESS_LIST_KEY = 'ADDRESS_LIST_KEY';
export const ADDRESS_SYMBOL_LIST_KEY = 'ADDRESS_SYMBOL_LIST_KEY';
export const RESERVE_DATA = 'RESERVE_DATA';
export const LATEST_FETCHED_RESERVE_DATA = 'LATEST_FETCHED_RESERVE_DATA';
export const MILI_SEC = 1000;
export const MINUTE = 60;